### ISSUE TITLE
Error when used with a recent version of disko

### ISSUE THREAD

**Issue by kilianar** [numtide/nixos-anywhere-examples#1]
**Describe the bug**
I have recently begun exploring [nixos-anywhere](https://github.com/numtide/nixos-anywhere/) and encountered an error. The example configuration provided in this repository is linked in the [quickstart section](https://numtide.github.io/nixos-anywhere/quickstart.html). Unfortunately, this configuration leads to an error when used with the latest version of disko.

```
error: The option `disko.devices.disk."/dev/sda".content.partitions."[definition 1-entry 2]".content._pkgs' is read-only, but it's set multiple times. Definition values:
  - In `/nix/store/6b90nww6znqp29mg4zzap8rz6z75kwnn-source/lib/types/mdraid.nix': <function>
  - In `<unknown-file>': <function>
```

**To Reproduce**

1. Use this flake with the most recent version of disko (for example, run `nix flake update`).
2. Run `nix run github:numtide/nixos-anywhere -- --flake .#hetzner-cloud --vm-test` as indicated in the quickstart.

**Expected Behavior**
The quickstart should provide a functional example, meaning this configuration should work with the latest versions of disko.

**Additional context**
The example given in the [README](https://github.com/numtide/nixos-anywhere/blob/e71ef009e630aa0b004872145ac386eb5a60b562/README.md) of nixos-anywhere seems to encounter the same error.

**Comment by god464** [comment]
Solution: https://github.com/nix-community/disko/issues/311

**Comment by kilianar** [comment]
The issue has been sorted with commit 00ac90f39181cf3614f6f4f1df2c7b9f741474c7, and it's running like a charm now. Thanks a lot to @Mic92 for tackling the problem!
